#!/usr/bin/env python3
# GENERATED by `dt agents build`. The Cursor guard adapter -- channel names come from argv, so
# one invocation can run a base and a channel guard set together. Predicates live in guard_core.py.
#
# The import is guarded because a broken guard_core exits non-zero, and a non-zero exit is a DENY
# in Cursor -- one bad file would block every write in every session. A guard that cannot load must
# be absent and loud, never fatal.
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

try:
    from guard_core import cursor_main
except Exception as exc:  # noqa: BLE001
    print(f"guard: cannot load guard_core ({exc!r}) -- failing OPEN, guards are NOT running",
          file=sys.stderr)
    sys.exit(0)

if __name__ == "__main__":
    cursor_main(*sys.argv[1:])
